# Generated by Django 6.0.2 on 2026-03-21 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField()),
                ('email', models.CharField()),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=14)),
                ('cv', models.FileField(upload_to='cvs')),
                ('date_craeted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='workplace_supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('requirements', models.CharField()),
                ('location', models.CharField()),
                ('duration', models.DateTimeField()),
                ('stipend', models.DecimalField(decimal_places=0, max_digits=10)),
                ('deadline', models.DateField()),
                ('dated_posted', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='internshipreport_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_file', models.FileField(upload_to='')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejeceted')], default='PENDING', max_length=12)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
        ),
        migrations.CreateModel(
            name='appplication_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='PENDING', max_length=12)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.internship')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.students')),
            ],
        ),
        migrations.CreateModel(
            name='academic_supervisor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('department', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=100)),
                ('specialization', models.CharField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.students')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_number', models.CharField()),
                ('content', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
