# Generated by Django 6.0.2 on 2026-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=14)),
                ('cv', models.FileField(upload_to='cvs')),
                ('date_craeted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
