# Generated by Django 6.0.4 on 2026-04-21 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='Academic_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='placement_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
