# Generated by Django 6.0.4 on 2026-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_weeklylog_academic_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
    ]
