# Generated by Django 6.0.4 on 2026-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('professionalism_score', models.PositiveIntegerField(default=0)),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
