# Generated by Django 6.0.2 on 2026-04-09 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Academic_supervisor',
        ),
        migrations.AddField(
            model_name='review',
            name='workplace_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to='role:Workplace_Supervisor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
