# Generated by Django 6.0.4 on 2026-04-09 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('reviews', '0002_remove_review_academic_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('professionalism_score', models.PositiveIntegerField(default=0)),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('weekly_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='logs.weeklylog')),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
